apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.mysql.label }}
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.mysql.namespace }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.label }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.label }}
    spec:
      containers:
      - image: {{ .Values.mysql.image.name }}:{{ .Values.mysql.image.tag }}
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        name: mysql
        resources: {}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.password }}
