apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.mysql.name }}-{{ .Values.mysql.postDelete.name }}
  namespace: {{ .Values.mysql.postDelete.namespace }}
  labels:
    app: {{ .Values.mysql.label }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded  
spec:
  template:
    metadata:
      name: {{ .Values.mysql.name }}-{{ .Values.mysql.postDelete.name }}
      labels:
        app: {{ .Values.mysql.label }}
    spec:
      containers:
      - name: {{ .Values.mysql.name }}-{{ .Values.mysql.postDelete.name }}
        imagePullPolicy: {{ .Values.mysql.postDelete.image.pullPolicy }}    
        image: {{ .Values.mysql.postDelete.image.name }}:{{ .Values.mysql.postDelete.image.tag }}
        volumeMounts:
        - mountPath: /tmp/db
          name: data
        - mountPath: /tmp/backup
          name: backup
        command: ["/bin/sh"]
        args: ["-c", "rm -rf /tmp/db/* && rm -rf /tmp/backup/*"]  
      restartPolicy: Never
      volumes:
      - name: data
        hostPath:
          path: {{ .Values.mysql.hostPath.db.path }}
      - name: backup
        hostPath:
          path: {{ .Values.mysql.hostPath.backup.path }}  
