apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.mysql.name }}-{{ .Values.mysql.postRollback.name }}
  namespace: {{ .Values.mysql.namespace }}
  labels:
    jobgroup: {{ .Values.mysql.label }}
  annotations:
    "helm.sh/hook": post-rollback
    "helm.sh/hook-delete-policy": hook-succeeded 
spec:
  template:
    metadata:
      name: {{ .Values.mysql.name }}-{{ .Values.mysql.postRollback.name }}
      labels:
        jobgroup: {{ .Values.mysql.label }}
    spec:
      containers:
      - name: {{ .Values.mysql.name }}-{{ .Values.mysql.postRollback.name }}
        imagePullPolicy: {{ .Values.mysql.postRollback.image.pullPolicy }}
        env:
        - name: DB_SERVER
          value: {{ .Values.mysql.name }}
        - name: DB_USER
          value: {{ .Values.mysql.user }} 
        - name: DB_PASS
          value: {{ .Values.mysql.password }}
        - name: RUN_ONCE
          value: "true"
        - name: DB_RESTORE_TARGET
          value: {{ .Values.mysql.postRollback.dbDumpPath }}/{{ .Values.mysql.postRollback.backupFile }}       
        image: {{ .Values.mysql.postRollback.image.name }}:{{ .Values.mysql.postRollback.image.tag }}
        volumeMounts:
        - mountPath: {{ .Values.mysql.postRollback.dbDumpPath }}  
          name: data 
        securityContext:
          runAsUser: 0 # Prerequisite for backup image
      restartPolicy: Never
      volumes:
      - name: data
        hostPath:
          path: {{ .Values.mysql.hostPath.backup.path }} 