apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.label }}
  name: mysql
  namespace: mysql
spec:
  ports:
  - name: {{ .Values.ports.source }}-{{ .Values.ports.target }}
    port: {{ .Values.ports.source }}
    protocol: TCP
    targetPort: {{ .Values.ports.target }}
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP