apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.mysql.label }}
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.mysql.namespace }}
spec:
  ports:
  - name: {{ .Values.mysql.ports.source }}-{{ .Values.mysql.ports.target }}
    port: {{ .Values.mysql.ports.source }}
    protocol: TCP
    targetPort: {{ .Values.mysql.ports.target }}
  selector:
    app: {{ .Values.mysql.label }}
  sessionAffinity: None
  type: ClusterIP